### PR TITLE
updated requirements installation for python dev env

### PR DESCRIPTION
**Pull request by konstan**
To be reviewed and merged after https://github.com/slipstream/SlipStreamClient/pull/318 

Connected to #111

### CODE REVIEW

**Comment by elegoff** [comment]
What was the reason for updating  _**docs/release_notes/candidate_releases.rst**_ ?

I would suggest to add also the following (which I checked is not mentioned in documentation)  : 

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

otherwise you get 

`ValueError: unknown locale: UTF-8 in Python`

**Comment by konstan** [comment]
RE: `docs/release_notes/candidate_releases.rst` - just to remove the page build warning.

Agreed, `UTF-8` related info is not in the documentation.  Where do you see it better located: in Dependencies http://ssdocs.sixsq.com/en/latest/developer_guide/dependencies.html (with a suggestion to add that into user's shell profile) or in http://ssdocs.sixsq.com/en/latest/developer_guide/building.html
?

**Comment by elegoff** [comment]
My personal preference would be  in Dependencies http://ssdocs.sixsq.com/en/latest/developer_guide/dependencies.html (with a suggestion to add that into user's shell profile)

**Comment by konstan** [comment]
Great.  Can you write this and push into this branch please?  I'll check it then.

**Pull request merged**
