### PR TITLE
add authentication configuration information

### PR DESCRIPTION
**Pull request by loomis**
Connected to #117.

### CODE REVIEW

**Comment by loomis** [comment]
Feedback from everyone is welcome.

The following specific feedback would be appreciated:
  * @konstan Comments on general configuration methods and clarity of the process
  * @cjdcordeiro Any information that should be added to the OIDC/Keycloak section or links to documentation on our configuration of Keycloak for SlipStream.

**Comment by loomis** [comment]
The main page is [here](http://ssdocs.sixsq.com/en/draft/administrator_guide/authentication.html). There were also changes in the cURL sections linked from this page.  Once the old authentication methods are removed other pages will also need to be cleaned up.

**Comment by mebster** [comment]
Couple of minor comments:
- I would use "<something>" instead of "_something_" for things to replace
- What happens if we do the post a second time?  Do we still get a 201?  Are we suppose to delete before reposting if we change the configuration?

**Comment by mebster** [comment]
Grr... markdown swallowed my edits.  Please check the raw text for the something thing above.

**Comment by cjdcordeiro** [comment]
I have nothing to point out. It is very abstracting of which OIDC "IdP" one uses so that's good. If you want to provide a technical example on how we've setup our Keycloak instance to test the OIDC authentication with IdP federations, you can find it here: https://github.com/SixSq/fed-id/README.md

**Pull request merged**
